@startuml

skinparam handwritten true

skinparam sequence {
ArrowColor DeepSkyBlue
ActorBorderColor DeepSkyBlue
LifeLineBorderColor blue
LifeLineBackgroundColor #A9DCDF

ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue

ParticipantFontColor #333

ActorBackgroundColor aqua
ActorFontColor DeepSkyBlue
ActorFontSize 17
ActorFontName Aapex
}


start

: Understand Industry Needs and Skills Required;
: Understand the Impact of Skills
- What skill has most impact?
- What should we focus on?;
: Determine How to Acquire Necessary Skills
- Developer => DataScientist
- DevOps => DataEngineer
- (Junior / Senior)
- etc.;
: What are State-of-the-Art Tools for Data Scientists & Data Engineers?;
: Create learning paths for various people involved; 


stop

@enduml
