# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic/
    watch: true

log:
  level: DEBUG
api:
  insecure: true
entryPoints:
  web:
    address: ":80"
