# Base Image
FROM ollama/ollama

RUN apt-get install -y curl gpg

# Nvidia GPU Configuration
## Add the NVIDIA repository GPG key and configure the repository
RUN <<EOF
curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
    | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list \
    | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
    | tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
apt-get update
apt-get install -y nvidia-container-toolkit
EOF

# defaults
# ENV OLLAMA_HOST=0.0.0.0
# ENV OLLAMA_MODELS=/root/.ollama/models

# the model
# ENV MODEL=llama2

# Command to run (assumes the correct command is `ollama run`)
# Use the shell form to ensure environment variable is used
# CMD ollama run $MODEL

ENTRYPOINT ["/bin/ollama"]
CMD ["serve"]
