FROM substratusai/vllm:latest

# Install nano and supervisor for better debugging 
RUN apt-get update && apt-get install -y nano supervisor && \
    rm -rf /var/lib/apt/lists/*

# run entrypoint as service for same reason

RUN { \
    echo '[supervisord]'; \
    echo 'nodaemon=true'; \
    echo '[unix_http_server]'; \
    echo 'file=/var/run/supervisor.sock'; \  
    echo '[supervisorctl]'; \
    echo 'serverurl=unix:///var/run/supervisor.sock'; \
    echo '[rpcinterface:supervisor]'; \
    echo 'supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface'; \
    echo '[program:myapp]'; \
    echo 'command=/usr/local/bin/entrypoint.sh'; \
    echo 'autostart=true'; \
    echo 'autorestart=true'; \
    echo 'stdout_logfile=/dev/stdout'; \
    echo 'stdout_logfile_maxbytes=0'; \
    echo 'stderr_logfile=/dev/stderr'; \
    echo 'stderr_logfile_maxbytes=0'; \
    } > /etc/supervisor/supervisord.conf

ENTRYPOINT ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]

