name: mEnv
channels:
  - defaults
dependencies:
  - pandas
  - spacy
  - networkx
  - scipy
  - conda-forge::neptune
  # find out what installed these? 
  # - ca-certificates
  # - certifi
  # - openssl
  - conda-forge::wikipedia-api
  - ipykernel
  - conda-forge::matplotlib
