apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.project_slug }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ cookiecutter.project_slug }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.project_slug }}
    spec:
      containers:
      - name: {{ cookiecutter.project_slug }}
        image: {{ cookiecutter.docker_user }}/{{ cookiecutter.project_slug }}:latest
        ports:
        - name: http
          containerPort: {{ cookiecutter.container_port }}
        # resources:
        #   limits:
        #     cpu: 1000m
        #     memory: 2G
        #   requests:
        #     cpu: 500m
        #     memory: 500M          
---
apiVersion: v1
kind: Service
metadata:
  name: {{ cookiecutter.project_slug }}
spec:
  type: ClusterIP
  selector:
    app: {{ cookiecutter.project_slug }}
  ports:
  - name: http
    port: {{ cookiecutter.host_port }}
    targetPort: {{ cookiecutter.container_port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ cookiecutter.project_slug }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: internal-nginx
  tls:
  - hosts:
    - {{ cookiecutter.k8s_ingress_name }}
  rules:
  - host: {{ cookiecutter.k8s_ingress_name }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ cookiecutter.project_slug }}
            port:
              name: "http"
