apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-coqui-tts-deployment
  labels:
    app: custom-coqui-tts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-coqui-tts
  template:
    metadata:
      labels:
        app: custom-coqui-tts
    spec:
      containers:
      - name: custom-coqui-tts-container
        image: frank1147/custom-coqui-tts:latest  
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: custom-coqui-tts-deployment
spec:
  type: ClusterIP
  selector:
    app: custom-coqui-tts-deployment
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
