apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: custom-coqui-tts-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: coqui.7frank.internal.jambit.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: custom-coqui-tts-service
            port:
              number: 80
